---
title: Su diccionario
author: Alberto Torrejón Valenzuela
date: '2020-11-28'
categories:
  - Diccionario
tags:
  - Ella
slug: diccionario-de-ella
---

<br>

<center><h1 class = "primerapalabra">**Su diccionario**</h1></center>

<br>

<div class = "primerapalabra"> <span class = "salmon"> Amor </span> </div>
<br>
<div class="just"> Hacer las cosas sin esperar nada a cambio solamente porque te sale del corazón, ya sea pareja, amigos, familiares, etc. Estar para esa persona, es confianza, comunicación, empatía, independencia, respeto, escucha activa.. el amor es lo q mueve el mundo…
</div>

<br><br>

<div class = "primerapalabra"> <span class = "lila"> Libertad </span> </div>
<br>
<div class="just"> Cuando pienso en libertad, pienso por una parte en la libertad de expresar tus pensamientos y sentimientos, pero a veces ahí entra la libertad del otro. Me refiero por ejemplo cuando dices algo que piensas pero estas ofendiendo a otra persona, ahí ya estás entrando en la libertad del otro. Está la libertad de poder expresarte tal y como eres y la libertad de pensar. Me acuerdo un día en terapia que le dije: “quiero sentirme libre con cómo soy y con cómo pienso”, refiriéndome a que yo misma a veces me ponía muchos límites entonces ahí me estaba quitando yo misma libertad. </div>

<br><br>

<div class = "primerapalabra"> <span class = "fg"> Hermana </span> </div>
<br>
<div class="just"> Cuando pienso en mi hermana la primera palabra que se me viene a la cabeza es incondicionalidad, es una persona que está ahí siempre pase lo que pase, la persona que más me quiere y encima al ser mi hermana mayor siempre intenta "cuidar" de mí, aunque sea desde la sombra. Pienso que es la persona que verdaderamente no me fallaría nunca, quitando a mis padres claro, pero mi hermana es la que mejores consejos me puede dar. </div>

<br><br>

<div class = "primerapalabra"> <span class = "dgr"> Beso </span> </div>
<br>
<div class="just"> Pues no te lo voy a decir, ya lo descubrirás... </div>

<br><br>

<div class = "primerapalabra"> <span class = "salmon"> Sexo </span> </div> 
<br>
<div class="just"> Pues para mí tener una relación sexual es entregarse a la otra persona, es donde no existen límites, es una forma más de expresarse que muchas veces no le damos la importancia que se merece. Obviamente hay relaciones por puro disfrute donde no tiene por qué haber sentimientos de por medio, pero cuando se tiene una relación con sentimientos es (para mi) muchísimo mejor, porque ahí puedes, a parte de disfrutar más aún, demostrar todo lo que sientes. Más de una vez cuando he sentido muchísimo por alguien y le he dado un abrazo por ejemplo, he sentido esas ganas de fundirme con esa persona y lo cierto es q teniendo una relación sexual es lo más parecido a eso. </div>

<br><br>

<div class = "primerapalabra"> <span class = "db"> Miedo </span> </div>
<br>
<div class="just"> ... </div>

<br>
